name: Build Laminar Mesh Report PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'Mesh_Files/**'
      - '.github/workflows/report-pdf.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc \
            texlive-xetex \
            texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra \
            lmodern texlive-plain-generic

      # Build inside Mesh_Files so relative image paths resolve
      - name: Build PDF with Pandoc
        working-directory: Mesh_Files
        run: |
          pandoc Laminar_Mesh_Report.md \
            --from=gfm+tex_math_dollars \
            --pdf-engine=xelatex \
            -V geometry:margin=1in \
            -o Laminar_Mesh_Report.pdf

      # Publish Mesh_Files/ (html preview of md + pdf) to GitHub Pages
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: Mesh_Files

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
